---
abstract: 'interpolate Perl variables into SQL statements'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  File::Temp: 0
  Test::Differences: 0
  Test::More: 0.88
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Interpol
requires:
  Carp: 0
  DBIx::Simple: 0
  Exporter::Tidy: 0
  Object::Tiny::Lvalue: 0
  perl: 5.012
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/SQL-Interpol/issues
  homepage: http://github.com/ap/SQL-Interpol
  repository: git://github.com/ap/SQL-Interpol
version: 1.002
